"""Branded ReportLab PDF deliverables.

Four document types:
  1. Individual anonymous feedback PDF   (student-facing)
  2. Team self-reported contribution PDF  (team-facing)
  3. Instructor section summary PDF       (instructor-only)
  4. Instructor confidential feedback PDF  (instructor-only)

Privacy rule enforced by build_individual_pdf: each student PDF contains ONLY
that student's name/team — no cross-student data leakage.
"""
from __future__ import annotations

import io
import math
from typing import List

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.utils import simpleSplit
from reportlab.pdfgen import canvas

from . import branding as B
from .grading import StudentResult, TeamResult

PAGE_W, PAGE_H = letter
MARGIN = 0.75 * inch


# --------------------------------------------------------------------------- #
# Low-level helpers
# --------------------------------------------------------------------------- #
def _header(c: canvas.Canvas, title: str, subtitle: str = "") -> float:
    c.setFillColor(B.NAVY)
    c.rect(0, PAGE_H - 1.15 * inch, PAGE_W, 1.15 * inch, fill=1, stroke=0)
    c.setFillColor(B.GREEN_LIGHT)
    c.rect(0, PAGE_H - 1.20 * inch, PAGE_W, 0.06 * inch, fill=1, stroke=0)
    c.setFillColor(B.WHITE)
    c.setFont("Helvetica-Bold", 20)
    c.drawString(MARGIN, PAGE_H - 0.62 * inch, B.BRAND)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(MARGIN, PAGE_H - 0.82 * inch, B.TAGLINE)
    c.setFont("Helvetica-Bold", 13)
    c.drawRightString(PAGE_W - MARGIN, PAGE_H - 0.62 * inch, title)
    if subtitle:
        c.setFont("Helvetica", 9)
        c.drawRightString(PAGE_W - MARGIN, PAGE_H - 0.82 * inch, subtitle)
    return PAGE_H - 1.5 * inch


def _footer(c: canvas.Canvas, note: str = "") -> None:
    c.setFillColor(B.GREY)
    c.setFont("Helvetica", 7.5)
    c.drawString(MARGIN, 0.5 * inch, note or "Generated by PeerParley — confidential")
    c.drawRightString(PAGE_W - MARGIN, 0.5 * inch, "peerparley")


def _wrap(c, text, x, y, width, font="Helvetica", size=10, leading=14, color=B.NAVY):
    c.setFont(font, size)
    c.setFillColor(color)
    for line in simpleSplit(text, font, size, width):
        if y < MARGIN + 0.5 * inch:
            c.showPage()
            y = PAGE_H - MARGIN
            c.setFont(font, size); c.setFillColor(color)
        c.drawString(x, y, line)
        y -= leading
    return y


def _is_nan(x) -> bool:
    try:
        return math.isnan(float(x))
    except (TypeError, ValueError):
        return True


def _grade_meter(c, x, y, w, signed_pct):
    """Horizontal meter centered on 0, range -15..+15."""
    h = 0.28 * inch
    c.setFillColor(B.GREY_LIGHT)
    c.roundRect(x, y, w, h, 4, fill=1, stroke=0)
    mid = x + w / 2
    c.setStrokeColor(B.GREY)
    c.setLineWidth(1)
    c.line(mid, y - 2, mid, y + h + 2)
    frac = max(-1, min(1, signed_pct / 15.0))
    col = B.grade_color(signed_pct)
    c.setFillColor(col)
    if frac >= 0:
        c.roundRect(mid, y + 3, (w / 2) * frac, h - 6, 3, fill=1, stroke=0)
    else:
        bw = (w / 2) * abs(frac)
        c.roundRect(mid - bw, y + 3, bw, h - 6, 3, fill=1, stroke=0)
    c.setFillColor(B.NAVY)
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(x + w / 2, y + h + 6,
                        f"{'+' if signed_pct >= 0 else ''}{signed_pct:g}% vs team score")


def _perf_pill(c, x, y, label):
    colors = {"High": B.GREEN, "Expected": B.GREY, "Adequate": B.GREY, "Low": B.AMBER}
    col = colors.get(label, B.GREY)
    w = 1.2 * inch
    c.setFillColor(col)
    c.roundRect(x, y, w, 0.26 * inch, 8, fill=1, stroke=0)
    c.setFillColor(B.WHITE)
    c.setFont("Helvetica-Bold", 9)
    c.drawCentredString(x + w / 2, y + 0.08 * inch, label.upper())


# --------------------------------------------------------------------------- #
# 1. Individual anonymous feedback PDF (student-facing)
# --------------------------------------------------------------------------- #
def build_individual_pdf(m: StudentResult, eval_no: str = "", course: str = "") -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    sub = f"Evaluation {eval_no}" if eval_no else ""
    y = _header(c, "Peer Feedback", sub)

    c.setFillColor(B.NAVY)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(MARGIN, y, m.name)
    c.setFont("Helvetica", 10)
    c.setFillColor(B.GREY)
    meta = f"Team {m.team}" + (f"  ·  {course}" if course else "")
    c.drawString(MARGIN, y - 16, meta)
    y -= 44

    _perf_pill(c, MARGIN, y, m.performance)
    y -= 20
    _grade_meter(c, MARGIN, y - 6, PAGE_W - 2 * MARGIN, m.signed_pct)
    y -= 60

    # ---- rating-matrix dimension grades (+ self comparison + pay grade) ----
    dims = [("Team player", m.team_player, m.self_team_player),
            ("Quantity of work", m.quantity, m.self_quantity),
            ("Quality of work", m.quality, m.self_quality),
            ("Effect on the team", m.effect, m.self_effect)]
    if any(peer for _, peer, _ in dims):
        c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 11)
        c.drawString(MARGIN, y, "How your teammates rated you")
        y -= 8
        c.setStrokeColor(B.GREEN_LIGHT); c.setLineWidth(2)
        c.line(MARGIN, y, MARGIN + 2.6 * inch, y)
        y -= 18
        show_self = m.self_responded and any(s for _, _, s in dims)
        c.setFont("Helvetica-Bold", 8.5); c.setFillColor(B.GREY)
        c.drawString(MARGIN, y, "Dimension")
        c.drawString(MARGIN + 2.7 * inch, y, "Peers")
        if show_self:
            c.drawString(MARGIN + 3.5 * inch, y, "Your self-rating")
        y -= 14
        for label, peer, selfg in dims:
            c.setFont("Helvetica", 10); c.setFillColor(B.NAVY)
            c.drawString(MARGIN, y, label)
            c.setFont("Helvetica-Bold", 11)
            c.drawString(MARGIN + 2.7 * inch, y, peer or "—")
            if show_self:
                c.setFont("Helvetica", 10); c.setFillColor(B.GREY)
                c.drawString(MARGIN + 3.5 * inch, y, selfg or "—")
                c.setFillColor(B.NAVY)
            y -= 16
        if not _is_nan(m.pay_grade):
            c.setFont("Helvetica", 10); c.setFillColor(B.GREY)
            c.drawString(MARGIN, y, f"Pay grade: {m.pay_grade:.0%} of the team average "
                                    "(100% = an even share).")
            c.setFillColor(B.NAVY)
        y -= 26

    c.setFillColor(B.NAVY)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(MARGIN, y, "What your teammates said")
    y -= 8
    c.setStrokeColor(B.GREEN_LIGHT); c.setLineWidth(2)
    c.line(MARGIN, y, MARGIN + 2.2 * inch, y)
    y -= 18

    anon = [t for t in m.public_comments if t.strip()]
    if not anon:
        y = _wrap(c, "No written feedback was submitted for you this cycle.",
                  MARGIN, y, PAGE_W - 2 * MARGIN, "Helvetica-Oblique", 10, color=B.GREY)
    else:
        for i, txt in enumerate(anon, 1):
            y = _wrap(c, "“" + txt + "”", MARGIN, y, PAGE_W - 2 * MARGIN,
                      "Helvetica", 10, 15, B.NAVY)
            y -= 8

    _footer(c, "Anonymous peer feedback — shared only with you.")
    c.showPage()
    c.save()
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# 2. Team self-reported contribution PDF
# --------------------------------------------------------------------------- #
def build_team_contribution_pdf(team: TeamResult, eval_no: str = "") -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = _header(c, "Team Contributions", f"Team {team.team}")
    c.setFillColor(B.GREY)
    c.setFont("Helvetica", 9)
    c.drawString(MARGIN, y, "Self-reported allocation of 100 points across the team.")
    y -= 26

    c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 10)
    c.drawString(MARGIN, y, "Member")
    c.drawString(MARGIN + 3.0 * inch, y, "Avg received")
    c.drawString(MARGIN + 4.4 * inch, y, "Performance")
    y -= 6
    c.setStrokeColor(B.GREY_LIGHT); c.setLineWidth(1)
    c.line(MARGIN, y, PAGE_W - MARGIN, y); y -= 16

    for m in team.members:
        c.setFillColor(B.NAVY); c.setFont("Helvetica", 10)
        c.drawString(MARGIN, y, m.name)
        avg = (sum(m.received_breakdown) / len(m.received_breakdown)) if m.received_breakdown else 0
        c.drawString(MARGIN + 3.0 * inch, y, f"{avg:.1f} / {m.expected_share:g}")
        col = {"High": B.GREEN, "Expected": B.GREY, "Adequate": B.GREY,
               "Low": B.AMBER}.get(m.performance, B.GREY)
        c.setFillColor(col); c.setFont("Helvetica-Bold", 9)
        c.drawString(MARGIN + 4.4 * inch, y, m.performance)
        y -= 18
        if y < MARGIN + inch:
            _footer(c); c.showPage(); y = PAGE_H - MARGIN

    _footer(c, "Team contribution summary — shared with the whole team.")
    c.showPage(); c.save()
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# 3. Instructor section summary PDF
# --------------------------------------------------------------------------- #
def build_section_summary_pdf(teams: List[TeamResult], course: str = "",
                              eval_no: str = "") -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = _header(c, "Section Summary", course or "")
    c.setFillColor(B.GREY); c.setFont("Helvetica", 9)
    c.drawString(MARGIN, y, f"{len(teams)} teams  ·  "
                 f"{sum(len(t.members) for t in teams)} students"
                 + (f"  ·  Eval {eval_no}" if eval_no else ""))
    y -= 24

    for t in teams:
        if y < MARGIN + 1.4 * inch:
            _footer(c); c.showPage(); y = PAGE_H - MARGIN
        c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 12)
        c.drawString(MARGIN, y, f"Team {t.team}")
        c.setFont("Helvetica", 9); c.setFillColor(B.GREY)
        c.drawRightString(PAGE_W - MARGIN, y, f"Team score {t.team_score:g}")
        y -= 6
        c.setStrokeColor(B.GREEN_LIGHT); c.setLineWidth(1.5)
        c.line(MARGIN, y, PAGE_W - MARGIN, y); y -= 16
        c.setFont("Helvetica-Bold", 8); c.setFillColor(B.GREY)
        cols = [("Name", 0), ("TP", 2.5), ("Qn", 2.9), ("Ql", 3.3), ("Ef", 3.7),
                ("Pay", 4.1), ("Q", 4.7), ("Mult", 5.1), ("Grade Δ", 5.7), ("Perf", 6.5)]
        for label, dx in cols:
            c.drawString(MARGIN + dx * inch, y, label)
        y -= 13
        for m in t.members:
            c.setFont("Helvetica", 8); c.setFillColor(B.NAVY)
            c.drawString(MARGIN, y, m.name[:28])
            c.drawString(MARGIN + 2.5 * inch, y, m.team_player or "—")
            c.drawString(MARGIN + 2.9 * inch, y, m.quantity or "—")
            c.drawString(MARGIN + 3.3 * inch, y, m.quality or "—")
            c.drawString(MARGIN + 3.7 * inch, y, m.effect or "—")
            c.drawString(MARGIN + 4.1 * inch, y,
                         "" if _is_nan(m.pay_grade) else f"{m.pay_grade:.0%}")
            c.drawString(MARGIN + 4.7 * inch, y, f"{m.Q:g}")
            c.drawString(MARGIN + 5.1 * inch, y, f"{m.multiplier:g}")
            c.setFillColor(B.grade_color(m.signed_pct))
            c.drawString(MARGIN + 5.7 * inch, y,
                         f"{'+' if m.signed_pct >= 0 else ''}{m.signed_pct:g}%")
            c.setFillColor(B.NAVY)
            c.drawString(MARGIN + 6.5 * inch, y, m.performance[:9])
            y -= 13
            if y < MARGIN + inch:
                _footer(c); c.showPage(); y = PAGE_H - MARGIN
        y -= 12

    if y < MARGIN + 1.8 * inch:
        _footer(c); c.showPage(); y = PAGE_H - MARGIN
    c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 9)
    c.drawString(MARGIN, y, "What each column means"); y -= 14
    legend = [
        "TP / Qn / Ql / Ef = letter grades for Team Player, Quantity, Quality, Effect "
        "(from the 4-statement rating matrix).",
        "Pay = average received allocation vs the team average (100% = an even share).",
        "Q = written-comment support score (0-1); Mult = final grade multiplier.",
        "Grade Δ = signed adjustment vs the team score.",
        "Perf = performance from the forced ranking (High / Adequate / Low).",
    ]
    for ln in legend:
        y = _wrap(c, "• " + ln, MARGIN, y, PAGE_W - 2 * MARGIN,
                  "Helvetica", 8.5, 12, B.GREY)

    _footer(c, "Instructor section summary — confidential.")
    c.showPage(); c.save()
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# 4. Instructor confidential feedback PDF
# --------------------------------------------------------------------------- #
def build_confidential_pdf(teams: List[TeamResult], course: str = "",
                           eval_no: str = "") -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    y = _header(c, "Confidential Feedback", course or "")
    c.setFillColor(B.RED); c.setFont("Helvetica-Bold", 9)
    c.drawString(MARGIN, y, "INSTRUCTOR ONLY — do not distribute to students.")
    y -= 24

    for t in teams:
        for m in t.members:
            conf = [x for x in m.confidential_comments if x.strip()]
            if not conf:
                continue
            if y < MARGIN + 1.2 * inch:
                _footer(c); c.showPage(); y = PAGE_H - MARGIN
            c.setFillColor(B.NAVY); c.setFont("Helvetica-Bold", 10.5)
            c.drawString(MARGIN, y, f"{m.name}  ·  Team {t.team}")
            y -= 16
            for txt in conf:
                y = _wrap(c, "— " + txt, MARGIN + 0.1 * inch, y,
                          PAGE_W - 2 * MARGIN - 0.1 * inch, "Helvetica", 9.5, 13, B.NAVY)
                y -= 6
            y -= 8

    _footer(c, "Confidential instructor feedback.")
    c.showPage(); c.save()
    return buf.getvalue()
